### ISSUE TITLE
What is the role of "receptive field"?

### ISSUE THREAD

**Issue by timqqt** [idiap/attention-sampling#9]
Hi guys,

I am working on developing your algorithm. I am wondering what is the role of "receptive field" in your code? Why we need this to shift our sampling offset? Could you tell me your intuition about tuning this parameters? Thanks.

**Comment by angeloskath** [comment]
Hi,

The receptive field is used to map correctly the locations of the image to the locations of the sampling distribution. So imagine a network with a receptive field of 5, stride 1 and no padding. We feed a downsampled image 100x100 which results in 96x96 positions to sample from. The first position corresponds to the pixel at indices 2,2 and not 0,0 . This is why we need the receptive field. So we can properly map the indices to the downsampled first and the original image afterwards.

Let me know if you need more information.

Cheers,
Angelos

**Comment by angeloskath** [comment]
I am closing the issue but feel free to reopen it if you have further questions.

Angelos
